# Generated by Django 5.2 on 2025-04-26 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pic",
                    models.URLField(
                        blank=True, validators=[apps.core.validators.validate_image_url]
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=300)),
                ("followers", models.ManyToManyField(to="profiles.profile")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
