# Generated by Django 5.2.1 on 2025-05-17 06:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="create_date",
            field=models.DateField(
                auto_now_add=True, default=datetime.date(2025, 5, 17)
            ),
            preserve_default=False,
        ),
    ]
