# Generated by Django 5.2.1 on 2025-05-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_reaction_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="+", to="posts.tag"),
        ),
    ]
