# Generated by Django 5.2.1 on 2025-05-24 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator("^[-\\dA-Za-z]*$"),
                ],
            ),
        ),
    ]
