# Generated by Django 5.2.1 on 2025-05-29 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_tag_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reaction",
            name="at_most_one_reaction_target",
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", True), ("comment__isnull", False)),
                    models.Q(("post__isnull", False), ("comment__isnull", True)),
                    _connector="OR",
                ),
                name="exactly_one_reaction_target",
            ),
        ),
    ]
