# Generated by Django 5.2.1 on 2025-05-29 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_remove_reaction_at_most_one_reaction_target_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("user", "post", "comment"), name="unique_user_post_comment"
            ),
        ),
    ]
