# Generated by Django 5.2.1 on 2025-05-31 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_reaction_unique_user_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(
                blank=True,
                max_length=15000,
                validators=[django.core.validators.MinLengthValidator(1500)],
            ),
        ),
    ]
