# Generated by Django 5.2.1 on 2025-06-01 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                max_length=300,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                blank=True,
                max_length=18500,
                validators=[django.core.validators.MinLengthValidator(1850)],
            ),
        ),
    ]
