# Generated by Django 5.2.1 on 2025-06-19 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_remove_reaction_unique_user_post_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_owner_post_comment",
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("owner", "post"),
                name="unique_owner_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("owner", "comment"),
                name="unique_owner_comment",
            ),
        ),
    ]
