# Generated by Django 5.2.1 on 2025-06-21 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_alter_tag_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="posts.comment",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="posts.post",
            ),
        ),
    ]
